version: '3.4'

services:
  catalogdb:
     image: mongo
     command: mongod --port 27018

volumes:
   catalogdb_data:

networks:
  micro-app-network:
     name: micro-app-network
     driver: bridge