version: '3.4'

services:
  catalogdb:
    image: mongo
    command: mogod --port 27018

  catalogservice.api:
    image: ${DOCKER_REGISTRY-}catalogserviceapi
    build:
      context: .
      dockerfile: Service/CatalogService/CatalogService.api/Dockerfile

volumes:
  catalogdb_data:

networks:
  micro-app-networks:
    name: micro-app-network
    driver: bridge