version: '3.4'

services:
  catalogdb:
     container_name: catalogdb
     restart: always
     ports:
        - "27018:27018"
     volumes:
        - catalogdb_data:/data/db
     networks:
        - micro-app-network

  catalogservice.api:
     container_name: catalogservice-api
     environment:
       - ASPNETCORE_ENVIRONMENT=Docker
     restart: always
     depends_on:
       - catalogdb
     ports:
       - "7001:80"
     networks:
       - micro-app-network