version: '3.4'

services:
  catalogdb:
     image: mongo
     command: mongod --port 27018

  catalogservice.api:
     image: ${DOCKER_REGISTRY-}catalogserviceapi-api
     build:
       context: .
       dockerfile: Service/CatalogService/CatalogService.api/Dockerfile

volumes:
   catalogdb_data:

networks:
  micro-app-network:
     name: micro-app-network
     driver: bridge
